// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQZVor7NwlOAq8fFmYebS6wzdbUpOVkY',
    appId: '1:76757087131:web:35be2a25b86c2b5c22e73e',
    messagingSenderId: '76757087131',
    projectId: 'fir-todo-demo-app',
    authDomain: 'fir-todo-demo-app.firebaseapp.com',
    storageBucket: 'fir-todo-demo-app.appspot.com',
    measurementId: 'G-8ECXZVRGE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeBwd37b9yRdUiUipuATHy9-NgS57n940',
    appId: '1:76757087131:android:9fcd97c54e63ea1e22e73e',
    messagingSenderId: '76757087131',
    projectId: 'fir-todo-demo-app',
    storageBucket: 'fir-todo-demo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpASeb0FY_gE4QzrNpyG6m8W3_6wR1km4',
    appId: '1:76757087131:ios:70b1a0e27ca1fa7722e73e',
    messagingSenderId: '76757087131',
    projectId: 'fir-todo-demo-app',
    storageBucket: 'fir-todo-demo-app.appspot.com',
    iosBundleId: 'com.example.saasakiFirebaseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQZVor7NwlOAq8fFmYebS6wzdbUpOVkY',
    appId: '1:76757087131:web:d2f6823dc673718222e73e',
    messagingSenderId: '76757087131',
    projectId: 'fir-todo-demo-app',
    authDomain: 'fir-todo-demo-app.firebaseapp.com',
    storageBucket: 'fir-todo-demo-app.appspot.com',
    measurementId: 'G-HN5V2L7R98',
  );

}